'use client';

/**
 * Case4BriefingPanel
 * 
 * Tabbed interface for 3 stakeholder briefings.
 * Default: collapsed (Top 3 actions), expandable to show all.
 * Download generates .txt file via Blob.
 */

import React, { useState } from 'react';
import { StakeholderBriefing } from '@/app/lib/case4/demoCase4Data';

interface Case4BriefingPanelProps {
  briefings: StakeholderBriefing[];
  activeTab: string;
  onTabChange: (role: string) => void;
}

export default function Case4BriefingPanel({
  briefings,
  activeTab,
  onTabChange
}: Case4BriefingPanelProps) {
  const [expandedTabs, setExpandedTabs] = useState<Set<string>>(new Set());
  
  const activeBriefing = briefings.find(b => b.role === activeTab);
  if (!activeBriefing) return null;
  
  const isExpanded = expandedTabs.has(activeTab);
  const visibleActions = isExpanded ? activeBriefing.actions : activeBriefing.actions.slice(0, 3);
  const hasMore = activeBriefing.actions.length > 3;
  
  const toggleExpand = () => {
    setExpandedTabs(prev => {
      const next = new Set(prev);
      if (next.has(activeTab)) {
        next.delete(activeTab);
      } else {
        next.add(activeTab);
      }
      return next;
    });
  };
  
  const handleDownload = () => {
    const content = `
IT REVIEW BRIEFING
Role: ${activeBriefing.role}
Title: ${activeBriefing.title}
Priority: ${activeBriefing.priority.toUpperCase()}
Generated: ${new Date().toISOString()}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

ACTION ITEMS

${activeBriefing.actions.map((action, idx) => `
${idx + 1}. ${action.action}

   Rationale: ${action.rationale}
   ${action.risk_reduction ? `Risk Reduction: ${action.risk_reduction}` : ''}
   ${action.impact ? `Impact: ${action.impact}` : ''}
   ${action.details ? `Details: ${action.details}` : ''}
`).join('\n')}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

This is a demonstration briefing generated by Case 4 IT Review.
For actual production use, consult with relevant teams and update based on real data.
`.trim();
    
    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `IT_Review_Briefing_${activeBriefing.role.replace(/ /g, '_')}_2026-01-15.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };
  
  const getPriorityBadge = (priority: string) => {
    const styles = {
      high: 'bg-red-100 text-red-800',
      medium: 'bg-yellow-100 text-yellow-800',
      low: 'bg-green-100 text-green-800'
    };
    return (
      <span className={`px-2 py-1 rounded text-xs font-bold uppercase ${styles[priority as keyof typeof styles]}`}>
        {priority}
      </span>
    );
  };
  
  return (
    <div className="bg-white border-2 border-purple-300 rounded-xl p-4">
      <div className="flex items-center gap-2 mb-3">
        <span className="text-xl">📢</span>
        <h2 className="text-base font-bold text-slate-800">Role-Based Briefings</h2>
      </div>
      
      {/* Tabs */}
      <div className="flex gap-2 mb-4 border-b-2 border-slate-200">
        {briefings.map((briefing) => (
          <button
            key={briefing.role}
            onClick={() => onTabChange(briefing.role)}
            className={`px-4 py-2 font-bold text-sm transition-colors ${
              activeTab === briefing.role
                ? 'border-b-2 border-purple-600 text-purple-600'
                : 'text-slate-600 hover:text-slate-800'
            }`}
          >
            {briefing.role.split(' ')[0]}
          </button>
        ))}
      </div>
      
      {/* Briefing Content */}
      <div className="space-y-3">
        <div className="flex items-start justify-between">
          <div>
            <h3 className="font-bold text-slate-800">{activeBriefing.title}</h3>
            <p className="text-xs text-slate-600 mt-1">{activeBriefing.role}</p>
          </div>
          {getPriorityBadge(activeBriefing.priority)}
        </div>
        
        {/* Actions */}
        <div className="space-y-2">
          {visibleActions.map((action, idx) => (
            <div
              key={idx}
              className="border-2 border-slate-200 rounded-lg p-3 bg-slate-50"
            >
              <div className="flex items-start gap-2">
                <span className="flex-shrink-0 w-6 h-6 rounded-full bg-purple-600 text-white text-xs font-bold flex items-center justify-center">
                  {idx + 1}
                </span>
                <div className="flex-1 min-w-0">
                  <h4 className="font-bold text-sm text-slate-800 mb-1">
                    {action.action}
                  </h4>
                  <p className="text-xs text-slate-600 mb-1">
                    {action.rationale}
                  </p>
                  {(action.risk_reduction || action.impact || action.details) && (
                    <div className="text-xs text-slate-500 space-y-0.5 mt-2">
                      {action.risk_reduction && (
                        <p><strong>Risk Reduction:</strong> {action.risk_reduction}</p>
                      )}
                      {action.impact && (
                        <p><strong>Impact:</strong> {action.impact}</p>
                      )}
                      {action.details && (
                        <p><strong>Details:</strong> {action.details}</p>
                      )}
                    </div>
                  )}
                </div>
              </div>
            </div>
          ))}
        </div>
        
        {/* Expand/Collapse Button */}
        {hasMore && (
          <button
            onClick={toggleExpand}
            className="w-full px-4 py-2 bg-slate-100 hover:bg-slate-200 text-slate-700 rounded-lg transition-colors font-bold text-sm"
          >
            {isExpanded ? `← Show top 3 only` : `Show all ${activeBriefing.actions.length} actions →`}
          </button>
        )}
        
        {/* Download Button */}
        <button
          onClick={handleDownload}
          className="w-full px-4 py-2 bg-purple-600 hover:bg-purple-700 text-white rounded-lg transition-colors font-bold text-sm flex items-center justify-center gap-2"
        >
          <span>📥</span>
          Download Briefing
        </button>
      </div>
    </div>
  );
}


