/**
 * Bundle Static Loader (Phase 3)
 *
 * Provides static-import based bundle loading for runtime code.
 * Uses compile-time bundling (NO fs.readFileSync).
 *
 * Phase 2: Stub only (not used)
 * Phase 3: Will load from generated static imports
 */

import type { LoadedBundles } from './bundleLoader';
import yaml from 'js-yaml';

/**
 * Phase 3: Static imports will be generated by generate-bundle-imports.ts
 * For now, this is a stub that throws an error.
 */
export function loadBundlesFromStaticImports(): LoadedBundles {
  // Phase 3: This will import from bundleImports.generated.ts
  // For now, throw error indicating this is not yet implemented
  throw new Error(
    '[BundleStaticLoader] Static imports not yet generated. ' +
    'Phase 3: Run `npm run generate:bundle-imports` first.'
  );
}

/**
 * Check if static imports are available
 * Phase 3: Will check if bundleImports.generated.ts exists
 */
export function hasStaticImports(): boolean {
  // Phase 3: Will return true if bundleImports.generated.ts is present
  return false;
}

/**
 * Runtime-safe bundle loader
 * Selects appropriate loading strategy based on environment
 *
 * Strategy selection:
 * 1. If FLOW2_SKILL_REGISTRY !== 'true' → disabled (throws)
 * 2. If static imports available → use static (runtime-safe)
 * 3. If Node.js with fs → use fs-based loader (scripts only)
 * 4. Else → fail (Edge runtime without static imports)
 */
export function loadBundlesRuntimeSafe(): LoadedBundles {
  // Check if bundles enabled
  if (process.env.FLOW2_SKILL_REGISTRY !== 'true') {
    throw new Error('[BundleLoader] FLOW2_SKILL_REGISTRY not enabled');
  }

  // Phase 3: Prefer static imports for runtime
  if (hasStaticImports()) {
    console.log('[BundleLoader] Using static imports (runtime-safe)');
    return loadBundlesFromStaticImports();
  }

  // Phase 2-3: Allow fs-based for scripts only (detect Node context)
  if (typeof process !== 'undefined' && typeof require !== 'undefined') {
    // We're in Node.js - check if this is a script or runtime
    const isScript = process.argv.some(arg =>
      arg.includes('run-self-check') ||
      arg.includes('run-golden-regression') ||
      arg.includes('generate-bundle-imports') ||
      arg.includes('scripts/') ||
      arg.includes('tsx')
    );

    if (isScript) {
      // Scripts can use fs-based loading
      console.log('[BundleLoader] Using fs-based loading (scripts only)');
      const { loadAllBundles } = require('./bundleLoader');
      return loadAllBundles();
    } else {
      // Runtime code attempted to use fs-based loading
      if (process.env.NODE_ENV === 'development') {
        // Dev: Fail-fast
        throw new Error(
          '[BundleLoader] CRITICAL: Runtime code cannot use fs-based loading. ' +
          'Run `npm run generate:bundle-imports` and use static imports.'
        );
      } else {
        // Prod: Warn and force fallback to legacy
        console.warn(
          '[BundleLoader] WARNING: Runtime attempted fs-based loading. ' +
          'Forcing fallback to legacy constants.'
        );
        throw new Error('[BundleLoader] Bundles disabled - use legacy constants');
      }
    }
  }

  // Edge runtime without static imports
  throw new Error(
    '[BundleLoader] Edge runtime requires static imports. ' +
    'Run `npm run generate:bundle-imports` first.'
  );
}
